function dynPlotter_statespace_f = dynPlotter_ode(in1,in2,in3)
%DYNPLOTTER_ODE
%    DYNPLOTTER_STATESPACE_F = DYNPLOTTER_ODE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    24-Mar-2020 16:41:24

Dl = in1(4,:);
Dth = in1(6,:);
Dxv = in1(2,:);
b_l = in3(4,:);
b_th = in3(5,:);
b_xv = in3(3,:);
k_l = in3(7,:);
k_v = in3(6,:);
l = in1(3,:);
m_l = in3(2,:);
m_v = in3(1,:);
tau_l = in2(2,:);
tau_v = in2(1,:);
th = in1(5,:);
xv = in1(1,:);
t2 = cos(th);
t3 = sin(th);
t4 = Dth.^2;
t5 = th.*2.0;
t8 = 1.0./m_l;
t9 = 1.0./m_v;
t10 = -xv;
t6 = t2.^2;
t7 = sin(t5);
t11 = l+t10;
t12 = 1.0./t11;
dynPlotter_statespace_f = [Dxv;-t9.*t12.*(Dl.*b_l.*l+Dxv.*b_xv.*l+Dl.*b_l.*t10+Dth.*b_th.*t2+Dxv.*b_xv.*t10-k_l.*l.*tau_l-k_v.*l.*tau_v+k_l.*tau_l.*xv+k_v.*tau_v.*xv-k_l.*l.*t3.*tau_l+k_l.*t3.*tau_l.*xv+Dl.*b_l.*l.*t3+Dl.*b_l.*t3.*t10);Dl;t8.*t9.*t12.*(k_l.*l.*m_l.*tau_l.*-2.0e+2-k_l.*l.*m_v.*tau_l.*1.0e+2-k_v.*l.*m_l.*tau_v.*1.0e+2-l.*m_l.*m_v.*t2.*9.81e+2+k_l.*m_l.*tau_l.*xv.*2.0e+2+k_l.*m_v.*tau_l.*xv.*1.0e+2+k_v.*m_l.*tau_v.*xv.*1.0e+2+m_l.*m_v.*t2.*xv.*9.81e+2-l.^2.*m_l.*m_v.*t4.*1.0e+2-m_l.*m_v.*t4.*xv.^2.*1.0e+2+Dl.*b_l.*l.*m_l.*2.0e+2+Dl.*b_l.*l.*m_v.*1.0e+2+Dxv.*b_xv.*l.*m_l.*1.0e+2+Dth.*b_th.*m_l.*t2.*1.0e+2+Dth.*b_th.*m_l.*t7.*5.0e+1-Dl.*b_l.*m_l.*xv.*2.0e+2-Dl.*b_l.*m_v.*xv.*1.0e+2-Dxv.*b_xv.*m_l.*xv.*1.0e+2+Dl.*b_l.*l.*m_l.*t3.*2.0e+2-Dl.*b_l.*l.*m_l.*t6.*1.0e+2+Dxv.*b_xv.*l.*m_l.*t3.*1.0e+2-Dl.*b_l.*m_l.*t3.*xv.*2.0e+2+Dl.*b_l.*m_l.*t6.*xv.*1.0e+2-Dxv.*b_xv.*m_l.*t3.*xv.*1.0e+2-k_l.*l.*m_l.*t3.*tau_l.*2.0e+2+k_l.*l.*m_l.*t6.*tau_l.*1.0e+2-k_v.*l.*m_l.*t3.*tau_v.*1.0e+2+l.*m_l.*m_v.*t4.*xv.*2.0e+2+k_l.*m_l.*t3.*tau_l.*xv.*2.0e+2-k_l.*m_l.*t6.*tau_l.*xv.*1.0e+2+k_v.*m_l.*t3.*tau_v.*xv.*1.0e+2).*(-1.0./1.0e+2);Dth;t8.*t9.*t12.^2.*(Dth.*b_th.*m_l.*5.0e+1+Dth.*b_th.*m_v.*1.0e+2+l.*m_l.*m_v.*t3.*9.81e+2-m_l.*m_v.*t3.*xv.*9.81e+2+Dth.*b_th.*m_l.*cos(t5).*5.0e+1+Dl.*Dth.*l.*m_l.*m_v.*2.0e+2-Dth.*Dxv.*l.*m_l.*m_v.*2.0e+2-Dl.*Dth.*m_l.*m_v.*xv.*2.0e+2+Dth.*Dxv.*m_l.*m_v.*xv.*2.0e+2+Dl.*b_l.*l.*m_l.*t2.*1.0e+2+Dl.*b_l.*l.*m_l.*t7.*5.0e+1+Dxv.*b_xv.*l.*m_l.*t2.*1.0e+2-Dl.*b_l.*m_l.*t2.*xv.*1.0e+2-Dl.*b_l.*m_l.*t7.*xv.*5.0e+1-Dxv.*b_xv.*m_l.*t2.*xv.*1.0e+2-k_l.*l.*m_l.*t2.*tau_l.*1.0e+2-k_l.*l.*m_l.*t7.*tau_l.*5.0e+1-k_v.*l.*m_l.*t2.*tau_v.*1.0e+2+k_l.*m_l.*t2.*tau_l.*xv.*1.0e+2+k_l.*m_l.*t7.*tau_l.*xv.*5.0e+1+k_v.*m_l.*t2.*tau_v.*xv.*1.0e+2).*(-1.0./1.0e+2)];
